// Single source for every UI string. Never hardcode text in components.
// Use t("namespace.key") or t("namespace.key", { var: value }) for interpolation.
// Purely decorative / symbol-only content (icons, separators) is the one allowed escape.

export const STRINGS = {
  brand: {
    name: "DelTech MUN",
    tagline: "Model United Nations at Delhi Technological University",
  },

  landing: {
    sectionDetails: "Conference Details",
    sectionAgendas: "Committees & Agendas",
    sectionAwards: "Awards",
    sectionContacts: "Get in Touch",
    dateLabel: "Dates",
    venueLabel: "Venue",
    registrationClosed: "Registrations Closed",
  },

  marketing: {
    liveBriefing: "Live conference briefing",
    applicationsOpen: "Delegate applications open",
    applicationsClosed: "Applications paused",
    heroFallback:
      "A student-led arena for policy, persuasion, and the difficult work of finding common ground.",
    venuePending: "Venue brief pending",
    datesPending: "Schedule brief pending",
    activeCommittees: "active committees",
    listedPortfolios: "listed portfolios",
    openPortfolios: "open portfolios",
    openLabel: "open",
    continueBriefing: "Continue the briefing",
    doubleDelegation: "Double delegation",
    committeeTypes: {
      standard: "General Assembly",
      crisis: "Crisis",
      press: "International Press",
    },
    viewMatrix: "Inspect the live matrix",
    readDispatch: "Read the dispatch",
    orbitLabel: "Diplomatic network visualisation",
    orbitStatus: "Network online",
    orbitSignal: "Secretariat signal",
    principles: "Research · Speak · Negotiate · Draft · Chair · Publish · Research · Speak · Negotiate · Draft · Chair · Publish",
    processEyebrow: "The delegate journey",
    processTitle: "From application to the floor.",
    processBody:
      "The platform tracks every step without turning the conference into paperwork. Apply, receive a considered allotment, confirm your place, and arrive ready to negotiate.",
    processOneTitle: "File your brief",
    processOneBody: "Submit your experience, preferences, and the portfolio you want to represent.",
    processTwoTitle: "Secretariat review",
    processTwoBody: "Applications are reviewed against committee fit, experience, and live availability.",
    processThreeTitle: "Take the floor",
    processThreeBody: "Receive your allotment and payment brief, then prepare to enter committee.",
    committeesEyebrow: "Committee intelligence",
    committeesTitle: "Choose the room you want to understand.",
    committeesBody:
      "Every committee asks a different question and rewards a different kind of preparation. Read the agendas, understand the format, and choose deliberately.",
    committeeBriefPending: "Agenda brief being prepared by the secretariat.",
    matrixEyebrow: "Live allocation signal",
    matrixTitle: "See what is actually available.",
    matrixBody:
      "The public matrix reflects the secretariat’s current allotments, so delegates can make informed preferences without relying on forwarded spreadsheets.",
    matrixCta: "Open the portfolio matrix",
    awardsTitle: "Recognition earned under pressure.",
    contactsTitle: "A direct line to the secretariat.",
    contactsBody:
      "Registration, accommodation, and committee questions deserve a human answer.",
    finalEyebrow: "Delhi Technological University",
    finalTitle: "Your first committee can start here.",
    footerBrief: "Conference desk",
    footerExplore: "Explore",
    footerOperations: "Operations",
    footerSignal: "Built for the next motion.",
    footerLocation: "Delhi · India",
    teamLabel: "Team",
    organiserSignIn: "Organiser sign-in",
    availabilityEyebrow: "Live allocation signal · realtime",
    availabilityTitle: "The live matrix.",
    availabilityBody: "Every portfolio is a live signal. Allotments, pending payments, and confirmations move here as the secretariat acts.",
    availabilityCountsBody: "The secretariat is publishing live committee counts while keeping individual allotments private.",
    portfoliosStillOpen: "portfolios still open",
    committeeSignal: "Committee signal",
    countsDisclosure: "Counts update live. Individual portfolio decisions stay private until the secretariat publishes the full matrix.",
    matrixComingSoon: "Portfolio briefing in progress",
    matrixComingSoonBody: "This committee is live, but its portfolio roster has not been published yet.",
    statusAvailable: "Available",
    statusAllotted: "Allotted · payment pending",
    statusConfirmed: "Confirmed · paid",
    statusBlocked: "Not open",
    statusFull: "Full",
    teamEyebrow: "The secretariat · current term",
    teamTitle: "The people behind the placards.",
    teamBody: "The conference is built by people who care about the room, the research, and every delegate walking into it.",
    activeTeam: "active team members",
    teamEmpty: "The secretariat roster is being assembled.",
    instagramLabel: "{name} on Instagram",
    linkedinLabel: "{name} on LinkedIn",
    dispatchEyebrow: "Field notes · opinion · conference intelligence",
    dispatchTitle: "The Dispatch.",
    dispatchBody: "Ideas from inside the room and beyond it, written by the delegates, chairs, and organisers shaping the conference.",
    dispatchMark: "DelTech MUN dispatch",
    latestDispatch: "Latest transmission",
    anonymousAuthor: "Anonymous",
    dispatchEmpty: "The desk is quiet, for now.",
    dispatchEmptyBody: "The first dispatch is being prepared for publication.",
    quizLive: "Live room signal",
    quizTitle: "Enter the room.",
    quizBody: "Six digits put you inside the session. Enter the code on the host screen and get ready to vote, answer, and climb the board.",
    registrationEyebrow: "Delegate application · secure intake",
    registrationBriefLabel: "Before you begin",
    registrationBrief: "Keep your committee preferences, portfolio choices, contact details, and MUN experience ready. Your progress moves through five short briefs.",
    allDispatches: "All dispatches",
    registrationClosedEyebrow: "Delegate intake paused",
    registrationClosedTitle: "The application desk is closed.",
    registrationSuccessEyebrow: "Transmission received",
  },

  common: {
    save: "Save",
    cancel: "Cancel",
    next: "Next",
    back: "Back",
    submit: "Submit",
    loading: "Loading…",
    search: "Search",
    export: "Export",
    yes: "Yes",
    no: "No",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    close: "Close",
    view: "View details",
    copy: "Copy",
    retry: "Try again",
    continue: "Continue",
    finish: "Finish",
    apply: "Apply",
    themeDark: "Switch to dark theme",
    themeLight: "Switch to light theme",
    reset: "Reset",
    goBack: "Go back",
    uploading: "Uploading…",
    saving: "Saving…",
    sending: "Sending…",
    required: "Required",
    optional: "Optional",
    notAvailable: "N/A",
    toggleTheme: "Toggle colour theme",
  },

  nav: {
    home: "Home",
    availability: "Committees",
    blog: "Blog",
    register: "Register",
    quizJoin: "Join Quiz",
    adminDashboard: "Dashboard",
    signIn: "Sign in",
    signOut: "Sign out",
    myApplication: "My Application",
    openMenu: "Open navigation",
    closeMenu: "Close navigation",
  },

  register: {
    pageTitle: "Delegate Registration",
    pageSubtitle: "Complete all steps to submit your application.",
    steps: {
      personal: "Personal Details",
      preferences: "Committee Preferences",
      coDelegateOrPref2: "Co-delegate / Second Preference",
      accommodation: "Accommodation",
      undertaking: "Undertaking & Submit",
    },
    personal: {
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Your full name as on ID",
      emailLabel: "Email address",
      emailPlaceholder: "you@example.com",
      whatsappLabel: "WhatsApp number",
      whatsappPlaceholder: "+91 9876543210",
      altPhoneLabel: "Alternate phone",
      altPhonePlaceholder: "+91 9876543210",
      institutionLabel: "Institution",
      institutionPlaceholder: "Your college or university",
      institutionLockedNote: "Filled automatically because you selected “I am a DTU student”. Untick to edit.",
      isDtuLabel: "I am a DTU student",
      munExperienceLabel: "MUN experience",
      munExperiencePlaceholder: "List committees you have attended (if any)",
    },
    preferences: {
      pref1CommitteeLabel: "First preference committee",
      pref1PortfolioLabel: "First preference portfolio",
      pref1PortfolioPlaceholder: "Country / role you would like",
      pref2CommitteeLabel: "Second preference committee",
      pref2PortfolioLabel: "Second preference portfolio",
      pref2PortfolioPlaceholder: "Country / role you would like",
      unhrcOnlyNote:
        "UNHRC is a double-delegation committee. It will be your only preference.",
    },
    coDelegate: {
      sectionTitle: "Co-delegate details",
      sectionNote:
        "UNHRC requires two delegates per portfolio. Please provide your co-delegate's information.",
      fullNameLabel: "Co-delegate full name",
      emailLabel: "Co-delegate email",
      emailPlaceholder: "co@example.com",
      phoneLabel: "Co-delegate phone",
      institutionLabel: "Co-delegate institution",
      munExperienceLabel: "Co-delegate MUN experience",
    },
    accommodation: {
      sectionTitle: "Accommodation",
      needsLabel: "I need accommodation during the conference",
      outsideNcrLabel: "I am travelling from outside Delhi-NCR",
      note: "Accommodation is on a first-come, first-served basis. Tariff details will be shared over email.",
    },
    undertaking: {
      referenceLabel: "How did you hear about us?",
      referencePlaceholder: "Friend, Instagram, etc.",
      checkboxLabel:
        "I confirm that all information provided is accurate and I agree to abide by the rules of the conference.",
      submitButton: "Submit Application",
    },
    success: {
      title: "Application received!",
      message:
        "Thank you for registering. You will receive an email with your allotment and payment link once the secretariat processes your application.",
      trackTitle: "Your private tracking route",
      trackNote: "Bookmark this link. It is private to your application.",
    },
    closed: {
      title: "Registrations closed",
    },
  },

  validation: {
    required: "{field} is required.",
    invalidEmail: "Please enter a valid email address.",
    mustAccept: "You must accept the undertaking to proceed.",
    phoneInvalid: "Please enter a valid phone number.",
    minLength: "{field} must be at least {min} characters.",
    maxLength: "{field} must be at most {max} characters.",
    mustSelectCommittee: "Please select a committee.",
    mustSelectPortfolio: "Please enter a portfolio preference.",
    duplicatePreference: "Your two committee preferences must be different.",
    emailAlreadyRegistered:
      "An application with this email already exists.",
  },

  toast: {
    saved: "Changes saved.",
    allotted: "Portfolio allotted successfully.",
    paymentMarkedPaid: "Payment marked as paid.",
    emailSent: "Email sent.",
    importComplete: "{count} delegates imported.",
    errorGeneric: "Something went wrong. Please try again.",
    copied: "Copied to clipboard.",
    deleted: "Record deleted.",
    settingUpdated: "Setting updated.",
    stringOverrideUpdated: "Copy updated.",
    migrationApplied: "Migration applied.",
    statusUpdated: "Status updated.",
    allotmentEmailQueued: "Allotment email queued.",
  },

  empty: {
    noRegistrations: "No registrations yet.",
    noPosts: "No posts yet.",
    noPortfolios: "No portfolios configured for this committee.",
    noResults: "No results match your search.",
    noPayments: "No payment records.",
    noCommittees: "No committees configured.",
    noFees: "No fee rows configured.",
    noStringOverrides: "No copy overrides. All strings use code defaults.",
  },

  admin: {
    nav: {
      overview: "Overview",
      registrations: "Registrations",
      allotment: "Allotment Board",
      payments: "Payments",
      committees: "Committees",
      fees: "Fees",
      blog: "Blog",
      quiz: "Quiz",
      config: "Config",
      strings: "Copy / Strings",
      checkin: "Check-in",
    },
    users: {
      inviteEmailPlaceholder: "person@deltech.edu",
    },
    team: {
      photoUploaded: "Photo uploaded.",
      uploadFailed: "Upload failed.",
    },
    overview: {
      totalRegistrations: "Total registrations",
      byStatus: "By status",
      byCommittee: "By committee",
      revenueCollected: "Revenue collected",
      accommodationRequests: "Accommodation requests",
      sourceBreakdown: "Source breakdown",
    },
    table: {
      headerName: "Name",
      headerEmail: "Email",
      headerInstitution: "Institution",
      headerCommittee: "Committee",
      headerStatus: "Status",
      headerSource: "Source",
      headerCreatedAt: "Registered",
      headerAmount: "Amount",
      headerPayStatus: "Payment",
      headerActions: "Actions",
      headerKey: "Key",
      headerValue: "Value",
      headerTemplate: "Template",
      headerSentAt: "Sent",
      selectAll: "Select all",
      clearSelection: "Clear selection",
      rowsSelected: "{count} selected",
    },
    drawer: {
      personalSection: "Personal details",
      preferencesSection: "Preferences",
      allotmentSection: "Allotment",
      paymentSection: "Payment",
      emailHistorySection: "Email history",
      coDelegateSection: "Co-delegate",
      editOnBehalf: "Edit on behalf",
      allotPortfolio: "Allot portfolio",
      markPaid: "Mark as paid",
      sendAllotmentEmail: "Send allotment email",
      resendEmail: "Resend",
      cancelRegistration: "Cancel registration",
      addNote: "Add note",
    },
    allotment: {
      selectPortfolio: "Select a portfolio",
      noSuggestions: "No matching candidates for this portfolio.",
      confirmAllot: "Confirm allotment",
      confirmAllotDescription:
        "Allot {portfolio} in {committee} to {delegate}? This cannot be undone.",
      onHoldWarning: "Portfolio is on hold by another admin.",
      doubleAllotError: "This portfolio has already been allotted.",
    },
    config: {
      tabGeneral: "General",
      tabCommittees: "Committees",
      tabFees: "Fees",
      tabStrings: "Copy / Strings",
      registrationToggleLabel: "Registration open",
      addCommittee: "Add committee",
      addPortfolio: "Add portfolio",
      bulkPastePortfolios: "Bulk-paste portfolios",
      bulkPastePlaceholder: "One portfolio per line",
      addFeeRow: "Add fee row",
      searchStrings: "Search copy keys…",
      editString: "Edit copy",
      resetString: "Reset to default",
    },
    import: {
      title: "Import delegates",
      uploadLabel: "Upload .xlsx or .csv",
      mapColumns: "Map columns",
      preview: "Preview",
      commit: "Commit import",
      rowsValid: "{count} rows valid",
      rowsWithErrors: "{count} rows with errors",
      savePreset: "Save column mapping as preset",
    },
  },

  // Society recruitment. The operational surface lives at /recruitment; the admin
  // dashboard only holds the control plane (see recruitment.control).
  recruitment: {
    brand: "Recruitment",
    nav: {
      overview: "My desk",
      gd: "Group discussions",
      pi: "Interviews",
      candidates: "Candidates",
      responses: "Form responses",
      audit: "Audit trail",
    },
    shell: {
      cycleLabel: "Cycle",
      roleLabel: "Your role",
      signOut: "Sign out",
      noCycleTitle: "No recruitment cycle is running",
      noCycleBody:
        "You will see your groups, candidates and session timers here as soon as an administrator opens a cycle.",
      deniedTitle: "No recruitment access",
      deniedBody: "You are not assigned to the active recruitment cycle.",
    },
    roles: {
      JC: "Junior Council",
      MAINTAINER: "Senior Council",
      ADMIN: "Administrative Council",
    },
    overview: {
      title: "My desk",
      description: "The sessions you are assigned to, and what still needs doing.",
      liveSessions: "Live now",
      upcoming: "Assigned to you",
      noSessions: "Nothing is assigned to you in this cycle yet.",
      pendingEvaluations: "Evaluations you still owe",
      allDone: "You are up to date.",
      openConsole: "Open console",
    },
    stage: {
      INTAKE: "Intake",
      GD_PENDING: "Awaiting GD",
      GD_ACTIVE: "In GD",
      GD_COMPLETE: "GD done",
      GD_BYPASSED: "GD skipped",
      PI_PENDING: "Awaiting interview",
      PI_ACTIVE: "In interview",
      PI_COMPLETE: "Interview done",
      DECISION: "Awaiting decision",
      CLOSED: "Closed",
    },
    result: {
      PENDING: "Pending",
      ON_HOLD: "Hold",
      SELECTED: "Selected",
      REJECTED: "Not selected",
      WITHDRAWN: "Withdrawn",
      DISQUALIFIED: "Disqualified",
    },
    sessionState: {
      NOT_STARTED: "Not started",
      ACTIVE: "Running",
      PAUSED: "Paused",
      COMPLETED: "Finished",
      ABORTED: "Aborted",
      STALE: "Stale",
    },
    attendance: {
      EXPECTED: "Expected",
      PRESENT: "Present",
      LATE: "Late",
      ABSENT: "Absent",
      REASSIGNED: "Reassigned",
    },
    pi: {
      inProgress: "Interviews in progress",
      resume: "Resume",
      startInterview: "Start interview",
      starting: "Starting…",
      searchPlaceholder: "Search by name, email, or branch",
      waiting: "{count} waiting",
      empty: "Nobody is waiting for an interview yet. Candidates arrive here once their GD is finished.",
      noMatches: "No candidates match that search.",
      waitingTab: "Waiting",
      pastTab: "Past interviews",
      pastEmpty: "No interview has been finished yet.",
      interviewed: "Interviewed",
    },
    groups: {
      titleGd: "Group discussions",
      titlePi: "Interviews",
      descriptionGd: "Create panels, run the timer, and record every evaluator's score.",
      descriptionPi: "Interview candidates with their full GD record in front of you.",
      newGroup: "New group",
      newPanel: "New interview",
      empty: "No groups yet.",
      emptyScoped: "You have not been assigned to any group in this cycle.",
      candidateCount: "{count} candidates",
      interviewCandidate: "Interview candidate",
      evaluationCount: "{count} evaluations",
      scheduled: "Scheduled",
      unscheduled: "Not scheduled",
      staffLabel: "Panel",
      titlePlaceholder: "Morning batch A",
      createTitleLabel: "Group title",
      searchCandidates: "Search by name, email, or branch",
      searchStaff: "Search the panel",
      panelCount: "{count} selected",
      noMatchingStaff: "No panel member matches that.",
      noMatchingCandidates: "No candidates match that search.",
      createCandidatesLabel: "Candidates",
      createStaffLabel: "Panel",
      createScheduleLabel: "Scheduled time",
      canEvaluateLabel: "May score",
      create: "Create group",
      creating: "Creating…",
      titleRequired: "Give the group a title to enable Create.",
      archive: "Archive",
      archived: "Archived",
      liveTab: "Live",
      pastTab: "Past",
      emptyLive: "No panels waiting to run.",
      emptyPast: "Nothing finished yet.",
      emptyPastScoped: "You have not finished a panel in this cycle.",
      finishedAt: "Finished",
      gdRecord: "Group discussion record",
      gdRecordEmpty: "No group discussion was scored for this candidate.",
      gdRecordBypassed: "GD was skipped for this candidate.",
      openDossierFull: "Open full dossier",
    },
    session: {
      start: "Start",
      pause: "Pause",
      resume: "Resume",
      finish: "Finish",
      abort: "Abort",
      reopen: "Reopen",
      elapsed: "Elapsed",
      planned: "Planned",
      startedAt: "Started",
      endedAt: "Ended",
      lastActivity: "Last activity",
      controllerYou: "you",
      notStartedYet: "Not started",
      staleWarning: "No activity for a while: this session may have been abandoned.",
      conflictToast: "Someone else changed this session. Showing the latest state.",
      alreadyRunning: "Already running.",
      alreadyFinished: "Already finished.",
      abortReasonLabel: "Why are you aborting?",
      reopenReasonLabel: "Why are you reopening this session?",
      finishing: "Finishing…",
      confirmFinish:
        "Finish this session? Every complete score is submitted now. They can still be revised afterwards.",
    },
    evaluation: {
      title: "Evaluation",
      yourScore: "Your score",
      aggregate: "Panel average",
notScored: "Not scored",
            evaluators: "{count} evaluators",
      remarksLabel: "Remarks",
      remarksPlaceholder: "What stood out, for better or worse?",
      recommendationLabel: "Recommendation",
      recommendationPlaceholder: "Choose a recommendation",
saving: "Saving…",
      readyToFinish: "Saved. Submitted when you finish.",
      savedIncomplete: "Saved. Score every criterion and choose a recommendation.",
            saveDraft: "Save draft",
      submit: "Submit",
      revise: "Revise",
      submitted: "Submitted",
      draft: "Draft",
      superseded: "Superseded",
      voided: "Voided",
      submittedBy: "by {name}",
      revisedNote: "Revised: the earlier version is kept in the record.",
      noChanges: "Nothing changed, so nothing was recorded.",
      // A locked form is one a JC has already submitted. Saying so is the whole
      // point: an inert form with no explanation reads as a broken one.
      lockedNote: "Your score is submitted and final. Ask a maintainer to change it.",
      needsScores: "Score every criterion to enable Revise.",
      needsRecommendation: "Choose Selected, Hold or Reject to enable Revise.",
      noneYet: "No evaluations recorded yet.",
      ownOnly: "You can see your own evaluations only.",
      notAnEvaluator: "You are on this panel to observe. Scoring was not enabled for you here.",
      overallOutOf: "{score} / 10",
    },
    recommendation: {
      ADVANCE: "Advance",
      HOLD: "Hold",
      REJECT: "Reject",
      SELECT: "Selected",
      RECONSIDER: "Reconsider",
    },
    selection: {
      exportAll: "Export all",
      exportSelected: "Export selected",
      emailSelected: "Email {count} selected",
      confirmSend:
        "Send the selection email to {count} candidate(s)? Anyone already emailed is skipped.",
      sentAll: "Sent to {sent} selected candidate(s).",
      sentPartial: "Sent to {sent}. {failed} failed and will be retried the next time you press this.",
      sentNone: "Everyone selected has already been emailed.",
      noneSelected: "Nobody has been selected yet.",
      allEmailed: "All {count} selected candidates have been emailed.",
      readyWithLink: "The WhatsApp group link is set and will be included.",
      readyNoLink:
        "No WhatsApp group link is set. The email will say the link follows separately. Set one in the cycle config to include it.",
    },
    candidates: {
      title: "Candidates",
      description: "Everyone in this recruitment cycle, and where they stand.",
      searchPlaceholder: "Name, email, branch…",
      stageFilter: "Stage",
      resultFilter: "Result",
      allStages: "All stages",
      allResults: "All results",
      allCandidatesTab: "All candidates",
      selectedCandidatesTab: "Final selections",
      empty: "No candidates match.",
      emptyCycle: "No candidates yet: import the form responses to get started.",
      count: "{count} candidates",
      openDossier: "Open dossier",
      searchAnswers: "Search answers",
      answersFiltered: "Showing candidates whose form answers mention \"{query}\". Clear to search names again.",
      pagination: "Candidate pages",
      pageOf: "Page {page} of {pages}",
      advanceToPi: "Advance to PI",
      advanceToGd: "Send to GD",
      advanceToDecision: "Move to decision",
      advanceAlready: "Already at that stage.",
      bypassGd: "Skip GD",
      bypassReasonLabel: "Why is GD being skipped for this candidate?",
      bypassReasonRequired: "Give a reason. It is kept on the audit trail.",
      bypassReasonReady: "Kept on the audit trail, and shown to the interview panel.",
      bypassConfirm: "Skip GD and send to interview",
      manualEditNote: "Hand-edited fields are protected from future imports.",
    },
    dossier: {
      profile: "Profile",
      formResponse: "Form response",
      history: "Recruitment history",
      gdRecord: "GD record",
      piRecord: "Interview record",
      noFormResponse: "No form response was imported for this candidate.",
      gdBypassedTitle: "GD intentionally skipped",
      gdBypassedBody: "Skipped by {actor} ({role}) on {date}.",
      gdBypassedNoReason: "No reason was recorded.",
      gdNotRequired: "This cycle does not run a GD for this candidate.",
      gdPending: "GD has not happened yet.",
      piPending: "The interview has not happened yet.",
      previousPiAttempts: "{count} earlier interview attempts",
      previousGdAttempts: "Previous GD attempts: {count}",
      duration: "Duration",
      importedFrom: "Imported from {source}",
      importedAt: "Imported {date}",
      noImportSource: "Added manually",
      reversedNote: "Reversed",
      email: "Email",
      phone: "Phone",
      branch: "Branch",
      year: "Year",
      unknownActor: "Unknown",
    },
    responses: {
      title: "Form responses",
      description:
        "Pull the Google Form response sheet, check what will change, then import. Re-importing the same sheet does nothing.",
      sourcesTitle: "Sheet sources",
      noSources: "No sheet is configured for this cycle yet.",
      noSourcesReadOnly:
        "No sheet is configured for this cycle yet. An admin sets that up; once it exists you can pull from it here.",
      addSource: "Add a sheet",
      editSource: "Edit",
      labelLabel: "Label",
      labelPlaceholder: "Main application form",
      sheetUrlLabel: "Google Sheets link",
      sheetUrlPlaceholder: "https://docs.google.com/spreadsheets/d/…",
      mappingTitle: "Column mapping",
      mappingHelp: "Match each candidate field to a column heading from the sheet.",
      mappingUnmapped: "Not mapped",
      save: "Save source",
      preview: "Preview",
      previewing: "Reading the sheet…",
      apply: "Import",
      applying: "Importing…",
      previewTitle: "What this import will do",
      duplicatesTitle: "Repeat submissions",
      duplicatesHelp: "These people submitted the form more than once. The most recent submission is kept; choose another row to override.",
      duplicateRow: "Row {row}",
      duplicateKept: "Keeping this one",
      duplicateUse: "Use this instead",
      previewFirst: "Preview this source first.",
      sourceIncomplete: "A label, a sheet link, and the name and email columns are all required.",
      alreadyApplied: "This exact sheet content has already been imported. Importing again will do nothing.",
      outcomeCreate: "New",
      outcomeUpdate: "Update",
      outcomeSkipUnchanged: "Unchanged",
      outcomeSkipDuplicate: "Duplicate",
      outcomeInvalid: "Invalid",
      protectedNote: "Protected: {fields}",
      invalidTitle: "Rows that will be skipped",
      importedResult:
        "{created} added, {updated} updated, {skipped} skipped, {invalid} invalid.",
      importedNothing: "Nothing changed: this sheet was already imported.",
      lastImport: "Last import",
      never: "Never",
      shareHint: 'Set the sheet to "Anyone with the link can view".',
    },
    control: {
      title: "Recruitment control",
      description:
        "Create and configure recruitment cycles, assign the council, and watch progress. The GD and interview screens live in the recruitment area.",
      openArea: "Open recruitment area",
      cyclesTitle: "Cycles",
      noCycles: "No recruitment cycle has been created yet.",
      newCycle: "New cycle",
      nameLabel: "Cycle name",
      namePlaceholder: "Recruitment 2026",
      slugLabel: "Slug",
      slugPlaceholder: "recruitment-2026",
      create: "Create cycle",
      configure: "Configure",
      monitorTitle: "Live progress",
      staffTitle: "Council",
      staffEmailLabel: "Email",
      staffRoleLabel: "Recruitment role",
      staffAdd: "Assign",
      staffRevoke: "Revoke",
      staffEmpty: "Nobody is assigned to this cycle yet.",
      staffNoteTitle: "Recruitment access is separate",
      staffNoteBody:
        "Assigning someone here gives them recruitment access only. It does not change what they can do in this dashboard.",
      stateLabel: "State",
      transitionTo: "Move to",
      transitionReasonLabel: "Reason",
      candidatesLabel: "Candidates",
      groupsLabel: "Groups",
      membersLabel: "Council",
      rubricTitle: "Evaluation rubric",
      rubricGd: "GD criteria",
      rubricPi: "Interview criteria",
      criterionLabel: "Label",
      criterionMax: "Out of",
      criterionWeight: "Weight",
      stagesTitle: "Stage rules",
      gdRequiredDefault: "New candidates need a GD",
      piRequiredDefault: "New candidates need an interview",
      selectionEmailTitle: "Selection email",
      selectionEmailHelp:
        "What selected candidates receive when you send the results. Sending is a separate button on the Candidates page, so you can set this up first.",
      selectionWhatsapp: "Members' WhatsApp group link",
      selectionWhatsappHint:
        "Leave it empty until you have the group. The email then says the link is coming separately, rather than not mentioning it.",
      selectionWhatsappInvalid: "That does not look like a link. It must start with http:// or https://.",
      selectionNote: "A line from the secretariat (optional)",
      selectionNotePlaceholder: "First meeting is on Saturday at 5pm in the AB3 seminar hall.",
      allowBypass: "Allow skipping GD",
      gdPlanned: "Planned GD length (minutes)",
      piPlanned: "Planned interview length (minutes)",
      saveConfig: "Save configuration",
      finaliseTitle: "Finalisation",
      finaliseDescription:
        "Selecting a candidate and adding them to the society are separate steps.",
      finalSelectedTitle: "Final selections",
      finalSelectedDescription:
        "Everyone marked Selected or Hold after their final interview. Decisions remain editable here.",
      emailSelected: "Email selected candidates",
      emailTemplatePending: "Email sending will be enabled when the final message format is added.",
      completeBeforeEmail: "Complete recruitment before sending the selection email.",
      noFinalSelected: "No candidates are in final selections yet.",
      addedToSociety: "Added to society",
      awaitingSociety: "Not added yet",
      awaitingRecruitment: "Selected, not yet added",
      recruit: "Add to society",
      recruiting: "Adding…",
      recruited: "In the society",
      recruitRoleLabel: "Society role",
      recruitDesignationLabel: "Roster designation (optional)",
      recruitDesignationPlaceholder: "Deputy Secretary General",
      alreadyRecruited: "Already added to the society.",
      staleSessionsTitle: "Stale sessions",
      staleSessionsBody: "{count} live sessions have had no activity for a while.",
      importErrorsTitle: "Import problems",
      importErrorsBody: "{count} rows were rejected by the last imports.",
    },
    audit: {
      title: "Audit trail",
      description: "Every recruitment action, including the ones that were refused.",
      empty: "No audit events match.",
      eventTypeFilter: "Event",
      outcomeFilter: "Outcome",
      actorFilter: "Actor",
      allEvents: "All events",
      allOutcomes: "All outcomes",
      outcomeSuccess: "Applied",
      outcomeRejected: "Refused",
      outcomeFailed: "Failed",
      previousState: "Before",
      newState: "After",
      reasonLabel: "Reason",
      immutableNote: "Audit records cannot be edited or deleted.",
      loadMore: "Load more",
      candidateFilter: "Candidate",
      candidateFilterPlaceholder: "Search by candidate name",
      rawRecord: "Raw record",
      refusedPrefix: "Refused",
      noCandidateMatch: "No candidate matches that name.",
      // Nested by segment because t() splits the key on ".", so a single key
      // containing a dot would never resolve.
      event: {
        candidate: {
          transition: "Candidate moved",
          override: "Candidate moved (override)",
          result: "Decision",
          bypassGd: "GD skipped",
          recruit: "Added to the society",
        },
        session: {
          start: "Session started",
          pause: "Session paused",
          resume: "Session resumed",
          finish: "Session finished",
          abort: "Session aborted",
        },
        evaluation: {
          draft: "Score saved",
          submit: "Score submitted",
          revise: "Score revised",
        },
        group: { create: "Panel created" },
        cycle: {
          create: "Cycle created",
          configure: "Cycle configured",
          transition: "Cycle state changed",
        },
        member: { assign: "Staff assigned", revoke: "Staff removed" },
        import: { configureSource: "Import source configured", apply: "Responses imported" },
        access: { denied: "Access refused" },
        action: { denied: "Action refused" },
      },
    },
    monitor: {
      total: "Total candidates",
      unassignedGd: "Unassigned (GD)",
      unassignedPi: "Unassigned (interview)",
      gdPending: "Awaiting GD",
      gdActive: "In GD",
      gdComplete: "GD done",
      gdBypassed: "GD skipped",
      piPending: "Awaiting interview",
      piActive: "In interview",
      piComplete: "Interview done",
      evaluationPending: "Evaluations outstanding",
      onHold: "On hold",
      selected: "Selected",
      rejected: "Not selected",
      withdrawn: "Withdrawn",
      staleSessions: "Stale sessions",
      importErrors: "Import errors",
      sessionsActive: "Sessions running",
      live: "Live",
      updated: "Updated {time}",
    },
    errors: {
      generic: "Something went wrong. Reload and try again.",
      denied: "You are not permitted to do that.",
      reasonRequired: "A reason is required.",
    },
  },

  checkin: {
    searchPlaceholder: "Name, email, institution…",
    statusPlaceholder: "Status",
    headerPortfolio: "Portfolio",
    checkInButton: "Check in",
    undoButton: "Undo",
    notConfirmedBadge: "Not confirmed",
    checkedInBadge: "Checked in",
    checkedInAt: "Checked in {time} by {by}",
    summary: "{checkedIn} / {confirmed} confirmed delegates checked in",
    deskEyebrow: "Registration desk",
    confirmButton: "Confirm check-in",
    alreadyCheckedIn: "Checked in at {time} by {by}",
    notConfirmedWarning: "This delegate is not marked CONFIRMED yet. Double-check before checking them in.",
    dtuLabel: "DTU student",
    accommodationLabel: "Needs accommodation",
    qrCaption: "Show this at the registration desk.",
    qrHeading: "Check-in QR",
  },

  payment: {
    payNowTitle: "Complete your payment",
    scanToPay: "Scan to pay via UPI",
    ivePaid: "I've paid",
    amountDue: "Amount due",
    rupees: "₹{amount}",
    referenceId: "Reference: {id}",
    instructions:
      "Scan the QR code with any UPI app (GPay, PhonePe, Paytm, etc.) and enter the exact amount.",
    pendingNote:
      "Your payment is being verified. This usually takes a few minutes.",
    confirmedNote: "Payment confirmed. Check your email for the allotment details.",
    failedNote: "Payment failed or expired. Please contact the secretariat.",
  },

  status: {
    REGISTERED: "Registered",
    ALLOTTED: "Allotted",
    PAYMENT_SENT: "Payment link sent",
    CONFIRMED: "Confirmed",
    CANCELLED: "Cancelled",
    WAITLISTED: "Waitlisted",
    payStatus: {
      PENDING: "Pending",
      SENT: "Link sent",
      PAID: "Paid",
      FAILED: "Failed",
      COMPED: "Comped",
      OFFLINE: "Offline / UPI",
    },
    portfolioStatus: {
      AVAILABLE: "Available",
      ON_HOLD: "On hold",
      ALLOTTED: "Allotted",
      BLOCKED: "Blocked",
    },
    allotmentLabel: "Your allotment",
    yourCommittee: "Committee",
    yourPortfolio: "Portfolio",
    paymentPending: "Payment pending",
    paymentConfirmed: "Payment confirmed",
    applicationConfirmed: "Your application is confirmed.",
  },

  blog: {
    writePlaceholder: "Tell your story…",
    titlePlaceholder: "Title",
    subtitlePlaceholder: "Subtitle (optional)",
    submitForReview: "Submit for review",
    saveDraft: "Save draft",
    pendingBadge: "Pending review",
    approvedBadge: "Published",
    changesRequestedBadge: "Changes requested",
    rejectedBadge: "Rejected",
    reviewNote: "Editor's note",
    readMin: "{n} min read",
    noTagsYet: "No tags",
    addCoverImage: "Add cover image",
    publishedOn: "Published {date}",
    by: "By {name}",
    moderationQueue: "Moderation queue",
    approve: "Approve",
    requestChanges: "Request changes",
    reject: "Reject",
    rejectionReasonPlaceholder: "Reason for rejection",
    imageUploadFailed: "Image upload failed.",
    coverUploadFailed: "Cover upload failed.",
  },

  quiz: {
    joinPrompt: "Enter your room code to join",
    roomCodePlaceholder: "e.g. 123456",
    joinButton: "Join",
    enterNickname: "Choose a nickname",
    nicknamePlaceholder: "Your display name",
    pickAvatar: "Pick an avatar",
    waitingToStart: "Waiting for the host to start…",
    participantsConnected: "{count} connected",
    answerReceived: "Answer received!",
    timeUp: "Time up",
    missedThisOne: "Voting closed before your answer. The next one is coming.",
    waitingForResults: "Waiting for the host to show the results…",
    waitingForNext: "Waiting for the next question…",
    correct: "Correct!",
    incorrect: "Not quite.",
    answerLocked: "Answer locked",
    revealIncoming: "The host is about to reveal it.",
    nextQuestionSoon: "Stay ready for the next one.",
    liveStandings: "Live standings",
    pointsShort: "pts",
    correctFeedback1: "Clean hit.",
    correctFeedback2: "You read that perfectly.",
    correctFeedback3: "That landed.",
    correctFeedback4: "Right on cue.",
    partialFeedback1: "Nearly there.",
    partialFeedback2: "That still moved your score.",
    partialFeedback3: "Close call. Points are points.",
    incorrectFeedback1: "Next one is yours.",
    incorrectFeedback2: "Shake it off and stay in the game.",
    incorrectFeedback3: "Good read, wrong turn.",
    incorrectFeedback4: "Reset. The next question is waiting.",
    movedUp: "Up {count}",
    movedDown: "Down {count}",
    heldPosition: "Holding",
    joinedBoard: "New",
    answerReveal: "Answer reveal",
    responsesIn: "{count} answers in",
    playersInRoom: "{count} in room",
    hostControls: "Host controls",
    liveQuestion: "Question live",
    audienceLobbyLive: "Audience lobby live",
    roomCode: "Room code",
    hostActionFailed: "That control did not reach the server. Nothing changed. Try once more.",
    pointsEarned: "+{points} points",
    timeLeft: "{seconds}s",
    votingLocked: "Voting closed",
    leaderboard: "Leaderboard",
    finalResults: "Final results",
    yourRank: "Your rank",
    playAgain: "Play again",
    endSession: "End session",
    nextSlide: "Next",
    prevSlide: "Previous",
    lockVoting: "Lock voting",
    unlockVoting: "Reopen voting",
    revealResults: "Reveal",
    presentButton: "Present",
    builderTitle: "Quiz builder",
    addSlide: "Add slide",
    slideType: {
      MCQ: "Multiple choice",
      TRUE_FALSE: "True or false",
      TYPE_ANSWER: "Type the answer",
      NUMERIC: "Number guess",
      WORDCLOUD: "Word cloud",
      SCALE: "Scale / rating",
      OPEN_TEXT: "Open text",
      CONTENT: "Content slide",
    },
    avatarGroups: {
      animals: "Creatures",
      faces: "Faces",
      things: "Things",
      world: "Places",
    },
    numericAverage: "Average guess",
    numericClosest: "Closest guess",
    noResponsesYet: "No answers yet",
    timeRemaining: "Time remaining",
    startBroadcast: "Start the broadcast →",
    noOneJoinedYet: "Nobody has joined yet. You can still start.",
    correctAnswer: "Correct answer",
    typeAnswerPlaceholder: "Type your answer",
    numericPlaceholder: "Your number",
    acceptedAnswersLabel: "Accepted answers",
    acceptedAnswersHelp: "One per line. Case and spacing are ignored.",
    exactMatchLabel: "Exact match (punctuation must match too)",
    targetLabel: "Correct number",
    toleranceLabel: "Tolerance (± earns partial credit)",
    unitLabel: "Unit (optional)",
    trueLabel: "True",
    falseLabel: "False",
    scoringTitle: "Scoring",
    basePointsLabel: "Points for a correct answer",
    speedWeightLabel: "Speed bonus weight",
    speedWeightHelp: "0 = speed does not matter. 0.5 = answering at the buzzer is worth half.",
    streakBonusLabel: "Streak bonus per answer in a row",
    partialCreditLabel: "Award partial credit for a partly-right answer",
    streakEarned: "+{points} streak bonus",
    closeEnough: "So close!",
    correctAnswerWas: "The answer was {answer}",
    modes: {
      POLL: "Poll",
      QUIZ: "Quiz (scored)",
    },
    joinTitle: "Join a session",
    invalidCode: "Room not found. Check the code and try again.",
    enterCodeFirst: "Enter a 6-digit room code above.",
    nicknameRequired: "Please enter a nickname.",
    nicknameTaken: "That nickname is already in this room. Pick another.",
    avatarRequired: "Please pick an avatar.",
    sessionEnded: "This session has ended. Thanks for playing!",
    submitAnswer: "Submit",
    addWord: "Add another word",
    yourRankLabel: "You are rank {rank}",
    showResults: "Show results",
    hideResults: "Hide results",
    connected: "{count} joined",
    slideProgress: "Slide {n} of {total}",
    voteCount: "{voted} / {total} voted",
    joinInstructions: "Go to {url} and enter code",
    getReady: "Get ready!",
    rankN: "#{n}",
    builder: {
      newPresentation: "New presentation",
      untitled: "Untitled presentation",
      titlePlaceholder: "Presentation title…",
      addOption: "Add option",
      optionPlaceholder: "Option {n}",
      correctAnswers: "Correct answer(s)",
      resultLayout: "Result layout",
      timer: "Timer",
      noTimer: "No timer",
      allowMultiple: "Allow multiple submissions",
      profanityFilter: "Profanity filter",
      scaleRange: "Scale range",
      minLabel: "Min label",
      maxLabel: "Max label",
      addStatement: "Add statement",
      statementPlaceholder: "Statement {n}",
      maxChars: "Character limit",
      responseLayout: "Response layout",
      bodyPlaceholder: "Body text…",
      promptPlaceholder: "Type your question or heading…",
      duplicate: "Duplicate",
      moveUp: "Move up",
      moveDown: "Move down",
      noSlides: "No slides yet. Add one below.",
      saved: "Saved",
      saving: "Saving…",
      unsaved: "Unsaved",
      acceptedAnswers: "Accepts",
      acceptedAnswersEmpty: "No accepted answer set yet",
      numericTolerance: "Within ±{n} earns partial credit",
      numericExact: "Only the exact number counts",
      themes: {
        presets: "Presets",
        classic: "Classic",
        ink: "Ink",
        gold: "Gold",
        ocean: "Ocean",
        forest: "Forest",
        custom: "Custom",
      },
      layouts: {
        BARS: "Bars",
        DONUT: "Donut",
        PIE: "Pie",
        DOTS: "Dots",
        SPEECH_BUBBLES: "Speech bubbles",
        FLOWING_GRID: "Flowing grid",
      },
    },
  },

  auth: {
    signInTitle: "Sign in to DelTech MUN",
    signInDescription: "Enter your email to receive a magic link, or sign in with your password.",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    sendLinkButton: "Send magic link",
    checkEmailTitle: "Check your inbox",
    checkEmailMessage: "We sent a sign-in link to your email. Click it to continue.",
    checkEmailExpiry: "The link expires in 30 minutes.",
    errorDefault: "Something went wrong. Please try again.",
    delegateNote: "No account needed to register as a delegate.",
    magicLinkTab: "Magic link",
    passwordTab: "Password",
    passwordLabel: "Password",
    passwordPlaceholder: "Your password",
    signInWithPasswordButton: "Sign in",
    invalidCredentials: "Invalid email or password.",
    signUpLinkText: "Create a delegate account",
    signInLinkText: "Sign in to existing account",
    signUpTitle: "Create your account",
    signUpDescription: "Sign up to track your allotment and payment status.",
    signUpPasswordTab: "Email & password",
    signUpMagicTab: "Magic link",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "Repeat your password",
    createAccountButton: "Create account",
    sendMagicLinkButton: "Send sign-in link",
    passwordMismatch: "Passwords do not match.",
    passwordTooShort: "Password must be at least 8 characters.",
    accountExists: "An account with this email already exists. Sign in instead.",
    nonDelegateAccount: "This email is reserved for an admin or author account.",
    passwordTooLong: "Password is too long.",
    emailRequired: "Enter your email address.",
    forgotPassword: "Forgot your password?",
    recoveryHint:
      "We will email you a one-time sign-in link. It takes you straight to your account page, where you can set a new password.",
    noPasswordYetHint:
      "Invited by an admin? You will not have a password yet. Use the magic link tab, then set one from your account page.",
    tooManyRequests: "Too many attempts. Wait a few minutes and try again.",
  },

  account: {
    title: "Your account",
    setPasswordTitle: "Set a password",
    changePasswordTitle: "Change your password",
    setPasswordNote:
      "You signed in with a magic link. Set a password and you can use it to sign in from now on.",
    changePasswordNote: "You will need your current password to change it.",
    currentPasswordLabel: "Current password",
    newPasswordLabel: "New password",
    savePasswordButton: "Save password",
    passwordSaved: "Password saved. Use it next time you sign in.",
    currentPasswordRequired: "Enter your current password.",
    currentPasswordWrong: "That current password is not right.",
    notSignedIn: "Your session expired. Sign in again.",
    backLink: "Back to your dashboard",
    navLabel: "Account",
  },

  dashboard: {
    title: "My Application",
    noRegistration: "No registration found",
    noRegistrationNote: "If you registered, make sure you used the same email address.",
    registerButton: "Register as a delegate",
    allotmentSection: "Your allotment",
    paymentSection: "Payment",
    notAllottedYet: "Your application is under review. You’ll receive your committee and portfolio by email once the secretariat processes it.",
    paymentPendingNote: "Payment details will appear once you’ve been allotted a committee.",
    confirmedMessage: "Your registration is confirmed. See you at the conference!",
  },

  email: {
    subjects: {
      magicLink: "Your DelTech MUN sign-in link",
      registrationReceived: "Your DelTech MUN registration is received",
      allotmentSent: "Your DelTech MUN allotment: {committee}, {portfolio}",
      coDelegateNotice: "You have been added as a co-delegate for {committee}",
      coDelegateRegistered: "You have been added as a co-delegate at DelTech MUN",
      paymentConfirmed: "Payment confirmed at DelTech MUN",
      paymentReminder: "Your DelTech MUN payment is still pending",
      blogApproved: 'Your article “{title}” has been published',
      blogChangesRequested: 'Changes requested on “{title}”',
      blogRejected: 'Update on your article “{title}”',
      recruitmentSelected: "You have been selected for DelTech MUN",
    },
    preview: {
      registrationReceived: "We have your application. Allotments will be sent soon.",
      allotmentSent: "You have been allotted a portfolio. Your payment link is inside.",
      paymentConfirmed: "Your registration is now complete.",
      paymentReminder: "Your allotment is waiting. Complete payment to secure your spot.",
    },
  },
} as const;

export type Strings = typeof STRINGS;

// Extracts all leaf dot-paths: "common.save", "register.steps.personal", etc.
type Leaves<T, P extends string = ""> = {
  [K in keyof T]: T[K] extends string
    ? P extends "" ? K & string : `${P}.${K & string}`
    : Leaves<T[K], P extends "" ? K & string : `${P}.${K & string}`>;
}[keyof T];

export type StringKey = Leaves<Strings>;

function getLeaf(obj: unknown, parts: string[]): string | undefined {
  let cur = obj;
  for (const p of parts) {
    if (cur == null || typeof cur !== "object") return undefined;
    cur = (cur as Record<string, unknown>)[p];
  }
  return typeof cur === "string" ? cur : undefined;
}

// Sync helper that uses compiled STRINGS. Safe in client and server components.
// For DB overrides in server components, use getStrings() from @/lib/settings.
export function t(key: StringKey, vars?: Record<string, string | number>): string {
  const value = getLeaf(STRINGS, key.split(".")) ?? key;
  if (!vars) return value;
  return value.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
}
